backend:
  name: github
  repo: hatwheels/artventures-website
  branch: prod
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow
site_url: https://artventures.me
display_url: https://artventures.me
collections:
  - name: "home"
    label: "Homepage"
    files:
      - label: "About Section"
        name: "about"
        file: "content/home/about.md"
        extension: 'md'
        fields:
          - label: Title
            name: title
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
          - label: Body
            name: body
            widget: object
            fields:
              - {label: english, name: en, widget: markdown}
              - {label: greek, name: gr, widget: markdown}
      - label: "Explore Section"
        name: "explore"
        file: "content/home/explore.md"
        fields:
          - label: Title
            name: title
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
          - label: Text of the Images
            name: images
            widget: list
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
          - label: Text of the button
            name: button
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
      - label: "Artists Section"
        name: "artists"
        file: "content/home/artists.md"
        fields:
          - label: Title
            name: title
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
          - label: Body
            name: body
            widget: object
            fields:
              - {label: english, name: en, widget: markdown}
              - {label: greek, name: gr, widget: markdown}
          - label: Testimonials
            name: testimonials
            widget: list
              fields:
                - label: quote
                  name: quote
                  widget: object
                  field:
                    - {label: english, name: en, widget: string}
                    - {label: greek, name: gr, widget: string}
                - label: author
                  name: author
                  widget: object
                  field:
                    - {label: english, name: en, widget: string}
                    - {label: greek, name: gr, widget: string}
          - label: Text of the button
            name: button
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
      - label: "Benefits Section"
        name: "benefits"
        file: "content/home/benefits.md"
        fields:
          - label: Benefits
            name: benefits
            widget: list
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Body
                name: body
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
            fields:
              - label: first
                name: benefit1
                widget: object
                fields:
                  - label: Title
                    name: title
                    widget: object
                    fields:
                      - {label: english, name: en, widget: string}
                      - {label: greek, name: gr, widget: string}
                  - label: Body
                    name: body
                    widget: object
                    fields:
                      - {label: english, name: en, widget: markdown}
                      - {label: greek, name: gr, widget: markdown}
      - label: "Media Section"
        name: "mdeia"
        file: "content/home/media.md"
        fields:
          - label: Title
            name: title
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
