[build]
  functions = "functions"

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://artventur.es/*"
  to = "https://artventures.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.artventur.es/*"
  to = "https://www.artventures.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://flamboyant-stonebraker-6fe6d3.netlify.app/*"
  to = "https://artventures.me/:splat"
  status = 301
  force = true