backend:
  name: git-gateway
  branch: prod
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow
site_url: https://artventures.me
display_url: https://artventures.me
collections:
  # Homepage
  - name: "home"
    label: "Homepage"
    files:
      # About Section
      - label: "About Section"
        name: "about"
        file: "content/home/about.md"
        extension: 'md'
        fields:
          - label: Title
            name: title
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
          - label: Text
            name: text
            widget: object
            fields:
              - {label: english, name: en, widget: markdown}
              - {label: greek, name: gr, widget: markdown}
      # Explore Section
      - label: "Explore Section"
        name: "explore"
        file: "content/home/explore.md"
        fields:
          - label: Title
            name: title
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
          - label: Text of the Images
            name: images
            widget: list
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
          - label: Button text
            name: button
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
      # Artists Section
      - label: "Artists Section"
        name: "artists"
        file: "content/home/artists.md"
        fields:
          - label: Title
            name: title
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
          - label: Text
            name: text
            widget: object
            fields:
              - {label: english, name: en, widget: markdown}
              - {label: greek, name: gr, widget: markdown}
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - label: Quote
                name: quote
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
              - label: Author
                name: author
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
          - label:  Button text
            name: button
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
      # Benefits Section
      - label: "Benefits Section"
        name: "benefits"
        file: "content/home/benefits.md"
        fields:
          - label: Benefits
            name: benefits
            widget: list
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
      # Media Section
      - label: "Media Section"
        name: "media"
        file: "content/home/media.md"
        fields:
          - label: Title
            name: title
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
  # Pages
  - name: pages
    label: Pages
    files:
      # Individuals page
      - label: Individuals
        name: individuals
        file: "content/pages/individuals.md"
        extension: 'md'
        fields:
          - label: Main
            name: main
            widget: object
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
              - label: Button text
                name: button
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
          - label: Advantages
            name: advantages
            widget: list
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
          - label: Rent
            name: rent
            widget: object
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
              - label: Button text
                name: button
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
      # Businesses page
      - label: Businesses
        name: businesses
        file: "content/pages/businesses.md"
        extension: 'md'
        fields:
          - label: Main
            name: main
            widget: object
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
              - label: Button text
                name: button
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
          - label: Button text
            name: button
            widget: object
            fields:
              - {label: english, name: en, widget: string}
              - {label: greek, name: gr, widget: string}
          - label: Advantages
            name: advantages
            widget: list
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - label: Quote
                name: quote
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
              - label: Author
                name: author
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
      # Hotels page
      - label: Hotels
        name: hotels
        file: "content/pages/hotels.md"
        extension: 'md'
        fields:
          - label: Main
            name: main
            widget: object
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
              - label: Button text
                name: button
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
          - label: Advantages
            name: advantages
            widget: list
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - label: Quote
                name: quote
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
              - label: Author
                name: author
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
          - label: Button text
            name: button
            widget: object
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: text
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
      # Artists page
      - label: Artists
        name: artists
        file: "content/pages/artists.md"
        extension: 'md'
        fields:
          - label: Main
            name: mainartists
            widget: object
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: par
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
              - label: Button
                name: button
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
          - label: Advantages
            name: advantages
            widget: list
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Text
                name: par
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
          - label: Earnings
            name: earnings
            widget: object
            fields:
              - label: Title
                name: title
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Earning items
                name: items
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: object
                    fields:
                      - {label: english, name: en, widget: string}
                      - {label: greek, name: gr, widget: string}
                  # - label: Text
                  #   name: par
                  #   widget: object
                  #   fields:
                  #     - {label: english, name: en, widget: markdown}
                  #     - {label: greek, name: gr, widget: markdown}
          # - label: Button
          #   name: button
          #   widget: object
          #   fields:
          #     - label: Title
          #       name: title
          #       widget: object
          #       fields:
          #         - {label: english, name: en, widget: string}
          #         - {label: greek, name: gr, widget: string}
          #     - label: Text
          #       name: par
          #       widget: object
          #       fields:
          #         - {label: english, name: en, widget: string}
          #         - {label: greek, name: gr, widget: string}
          # - label: Testimonials
          #   name: artisttestimonials
          #   widget: object
          #   fields:
          #     - label: Title
          #       name: title
          #       widget: object
          #       fields:
          #         - {label: english, name: en, widget: string}
          #         - {label: greek, name: gr, widget: string}
          #     - label: Testimonials
          #       name: items
          #       widget: object
          #       fields:
          #         - label: Quote
          #           name: quote
          #           widget: object
          #           fields:
          #             - {label: english, name: en, widget: markdown}
          #             - {label: greek, name: gr, widget: markdown}
          #         - label: Author
          #           name: author
          #           widget: object
          #           fields:
          #             - {label: english, name: en, widget: string}
          #             - {label: greek, name: gr, widget: string}
      # FAQ page
      - label: FAQ
        name: faq
        file: "content/pages/faq.md"
        extension: 'md'
        fields:
          - label: Questions & Answers
            name: qa
            widget: list
            fields:
              - label: Question
                name: q
                widget: object
                fields:
                  - {label: english, name: en, widget: string}
                  - {label: greek, name: gr, widget: string}
              - label: Answer
                name: a
                widget: object
                fields:
                  - {label: english, name: en, widget: markdown}
                  - {label: greek, name: gr, widget: markdown}
